/**
 * Skill provider: ships a snapshot of the public realtimeavatar.ai docs as
 * five on-demand skills (name + description in the catalog; the body loads
 * only when the model calls the `skill` tool or the user types /skill-name).
 *
 * Files live in `skills/*.md` with YAML-ish frontmatter (name, description,
 * snapshot, sources) generated by `scripts/sync-docs.mjs`.
 *
 * @module dsh-realtimeavatar/skills
 */
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { SKILL_NAMES } from './facts.js'

export const PROVIDER_NAME = 'dsh-realtimeavatar'
/** Bundled skills rank below every discovery root so a user's own copy can shadow them. */
export const BUNDLED_SKILL_RANK = 600
export const MAX_DESCRIPTION_CHARS = 400

/** Directory of the shipped skill files (next to lib/). */
export function defaultSkillsDir(): string {
  return fileURLToPath(new URL('../skills/', import.meta.url))
}

export interface SkillFrontmatter {
  name: string
  description: string
  snapshot?: string
  sources?: string
}

/** Parse the simple `key: value` frontmatter block; returns the body without it. */
export function parseFrontmatter(text: string): { data: Record<string, string>; body: string } {
  const normalized = text.replace(/\r\n/g, '\n')
  if (!normalized.startsWith('---\n')) return { data: {}, body: normalized }
  const end = normalized.indexOf('\n---\n', 4)
  if (end === -1) return { data: {}, body: normalized }
  const data: Record<string, string> = {}
  for (const line of normalized.slice(4, end).split('\n')) {
    const match = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(line)
    if (match !== null) data[match[1]] = match[2].trim().replace(/^['"]|['"]$/g, '')
  }
  return { data, body: normalized.slice(end + 5).replace(/^\n+/, '') }
}

/** The shape dsh's skill registry expects from a provider (structural; no dsh import). */
export interface SkillCandidate {
  name: string
  description: string
  whenToUse?: string
  invocation: { modelInvocable: boolean; userInvocable: boolean }
  source: 'bundled'
  provider: string
  resourceBase: { kind: 'directory'; path: string }
  rank: number
  locator: string
  path: string
  metadata?: Record<string, unknown>
}

export interface SkillDefinition extends SkillCandidate {
  content: string
}

export interface SkillProvider {
  name: string
  list(): Promise<SkillCandidate[]>
  get(candidate: SkillCandidate): Promise<SkillDefinition | undefined>
}

/** Build the provider over `skillsDir`. Missing files are skipped with one warning each. */
export function createSkillProvider(skillsDir: string = defaultSkillsDir(), warn: (message: string) => void = (m) => console.warn(m)): SkillProvider {
  let cached: SkillCandidate[] | null = null
  const warned = new Set<string>()
  const load = async (name: string): Promise<{ candidate: SkillCandidate; body: string } | null> => {
    const path = join(skillsDir, name + '.md')
    let text: string
    try {
      text = await readFile(path, 'utf8')
    } catch {
      if (!warned.has(name)) {
        warned.add(name)
        warn('[dsh-realtimeavatar] skill file missing: ' + path)
      }
      return null
    }
    const { data, body } = parseFrontmatter(text)
    const description = (data.description ?? '').slice(0, MAX_DESCRIPTION_CHARS)
    if (data.name !== name || description === '') {
      if (!warned.has(name)) {
        warned.add(name)
        warn('[dsh-realtimeavatar] skill file has bad frontmatter: ' + path)
      }
      return null
    }
    const candidate: SkillCandidate = {
      name,
      description,
      invocation: { modelInvocable: true, userInvocable: true },
      source: 'bundled',
      provider: PROVIDER_NAME,
      resourceBase: { kind: 'directory', path: skillsDir },
      rank: BUNDLED_SKILL_RANK,
      locator: pathToFileURL(path).href,
      path,
      metadata: { snapshot: data.snapshot ?? null, sources: data.sources ?? null },
    }
    return { candidate, body }
  }
  return {
    name: PROVIDER_NAME,
    async list() {
      if (cached !== null) return cached
      const out: SkillCandidate[] = []
      for (const name of SKILL_NAMES) {
        const loaded = await load(name)
        if (loaded !== null) out.push(loaded.candidate)
      }
      cached = out
      return out
    },
    async get(candidate) {
      const loaded = await load(candidate.name)
      if (loaded === null) return undefined
      return { ...loaded.candidate, content: loaded.body }
    },
  }
}
